#----------------------------------------------------------------------------------
# Site Settings
#----------------------------------------------------------------------------------

# Title of your site
title: AI Inside Out

# Short bio or description
description: "Your one-stop shop for all things AI"

# Site logo image such as corporate symbol
logo: /assets/images/logo.png

# Your website URL (e.g. https://<username>.github.io)
# Used for sitemap.xml and your RSS feed
url: https://fiona-bi.github.io

repository: fiona-bi/ai

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/ai"

# The site locale e.g. en-us
locale: en-us

# The site charset e.g. utf-8
charset: utf-8

# Discourage search engines to index the site
noindex: false

# Link to the favicon (Default: "/favicon.ico")
favicon:

# Link to the privacy policy
privacy_policy_link:

jquery_version: "1.12.4"

timezone: UTC

#----------------------------------------------------------------------------------
# Theme Settings
#----------------------------------------------------------------------------------
themes:
  # The active theme must exist in the themes folder.
  active: rapp

  rapp:
    header:
      title: AI Inside Out
      description: One-stop hub of all things AI<br />- AI news, learning, events, projects, and many more.
      banner_app: /assets/images/banner-app.jpg
      banner_image: /assets/images/banner.jpg


#----------------------------------------------------------------------------------
# Post Settings
#----------------------------------------------------------------------------------

# The permalink of posts
# For multilingual site, /:path/ is the only global permalink setting that works.
# Other permalink settings cannot prepend the post locale to the URL.
permalink: /:year/:month/:day/:title/

# Default settings of posts
default_post_settings: &default_post_settings
  layout: post
  permalink: /web/:categories/:year/:month/:day/:title/
  deleted: false
  has_sidebar: true
  read_time: true
  share: true
  related: true
  comments:
    enabled: true

pagination:
  page_size: 20

#----------------------------------------------------------------------------------
# Page Settings
#----------------------------------------------------------------------------------

# Default settings of pages
default_page_settings: &default_page_settings
  layout: page
  permalink: /:path/
  has_sidebar: false
  comments:
    enabled: false

page_templates:
  home:
  search:
  404:


#----------------------------------------------------------------------------------
# Learning Settings
#----------------------------------------------------------------------------------

# Default settings of learning
default_learning_settings: &default_learning_settings
  layout: post
  category: learning
  permalink: /web/learning/:path/
  deleted: false
  has_sidebar: false
  comments:
    enabled: false


#----------------------------------------------------------------------------------
# Project Settings
#----------------------------------------------------------------------------------

# Default settings of projects
default_project_settings: &default_project_settings
  layout: post
  category: project
  permalink: /web/projects/:path/
  deleted: false
  has_sidebar: false
  comments:
    enabled: false


#----------------------------------------------------------------------------------
# Company Settings
#----------------------------------------------------------------------------------

# Default settings of companies
default_company_settings: &default_company_settings
  layout: post
  category: company
  permalink: /web/companies/:path/
  deleted: false
  has_sidebar: false
  comments:
    enabled: false


#----------------------------------------------------------------------------------
# Celebrity Settings
#----------------------------------------------------------------------------------

# Default settings of celebrities
default_celebrity_settings: &default_celebrity_settings
  layout: post
  category: celebrity
  permalink: /web/celebrities/:path/
  type: profile
  deleted: false
  has_sidebar: false
  comments:
    enabled: false


#----------------------------------------------------------------------------------
# Event Settings
#----------------------------------------------------------------------------------

# Default settings of events
default_event_settings: &default_event_settings
  layout: post
  category: event
  permalink: /web/events/:path/
  deleted: false
  has_sidebar: false
  comments:
    enabled: false


#----------------------------------------------------------------------------------
# Newsletter Settings
#----------------------------------------------------------------------------------

# Default settings of newsletter issues
default_newsletter_settings: &default_newsletter_settings
  layout: none
  category: newsletter
  permalink: /web/newsletter/:path/
  deleted: false
  has_sidebar: false
  comments:
    enabled: false


#----------------------------------------------------------------------------------
# Taxonomy Settings
#----------------------------------------------------------------------------------

# You can overwrite the default taxonomy settings in individual taxonomy settings
default_taxonomy_settings: &default_taxonomy_settings
  layout: archive
  permalink: /:path/
  has_sidebar: true
  comments:
    enabled: false

taxonomies:
  category:
    name: Category
    settings: &category_settings
      taxonomy: category
      archive:
        taxonomy_field: categories
        taxonomy_query: item.categories contains page.name
        post_collection: # Default: posts
        where_exp: # Default: nil
        order_by: # Default: date
        order: # Default: DESC

  tag:
    name: Tag
    settings: &tag_settings
      taxonomy: tag
      archive:
        taxonomy_field: tags
        taxonomy_query: item.tags contains page.name
        post_collection: # Default: posts
        where_exp: # Default: nil
        order_by: # Default: date
        order: # Default DESC

  topic:
    name: Topic
    settings: &topic_settings
      taxonomy: topic
      archive:
        taxonomy_field: topics
        taxonomy_query: item.topics contains page.name


#----------------------------------------------------------------------------------
# Shortcodes
#----------------------------------------------------------------------------------
shortcodes:
  if:
    enabled: true
    settings:
  youtube:
    enabled: true
    settings:
  tradingview:
    enabled: true
    settings:
  note:
    enabled: false
    settings:
  tabs:
    enabled: false
    settings:
  accordion:
    enabled: false
    settings:
  codepen:
    enabled: false
    settings:


#----------------------------------------------------------------------------------
# Analytics
#----------------------------------------------------------------------------------
analytics:
  google:
    enabled: true
    settings:
      tracking_id:


#----------------------------------------------------------------------------------
# Comments
#----------------------------------------------------------------------------------
comments:
  disqus:
    enabled: true
    settings:
      shortname:
  discourse:
    enabled: false
    settings:
      server:
  facebook:
    enabled: false
    settings:
      appid:
      num_of_posts:
      colorscheme:


#----------------------------------------------------------------------------------
# Search
#----------------------------------------------------------------------------------
search:
  lunr:
    enabled: true
    settings:
      search_field_selector:              # Default: input.search_field
      search_result_container_selector:   # Default: auto-calculated based on search_field
      num_of_search_results:              # Default: 5
      highlight_search_terms:             # Default: false


#----------------------------------------------------------------------------------
# SEO
#----------------------------------------------------------------------------------
seo:
  opengraph:
    enabled: true
  twitter:
    enabled: true


#----------------------------------------------------------------------------------
# Site Verification
#----------------------------------------------------------------------------------
site_verification:
  google:
    enabled: false
    settings:
      verification_code:
  bing:
    enabled: false
    settings:
      verification_code:
  pinterest:
    enabled: false
    settings:
      verification_code:
  yandex:
    enabled: false
    settings:
      verification_code:


#----------------------------------------------------------------------------------
# Custom Settings
#----------------------------------------------------------------------------------




#----------------------------------------------------------------------------------
# System Settings
# DO NOT CHANGE if you do not know what you are doing
#----------------------------------------------------------------------------------

collections:
  terms:
    output: true
  sponsorships:
    output: true
  posts:
    output: true
  pages:
    output: true
  learning:
    output: true
  projects:
    output: true
  scholars:
    output: true
  companies:
    output: true
  celebrities:
    output: true
  events:
    output: true
  newsletter:
    output: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      <<: *default_post_settings
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      <<: *default_page_settings
  # _learning
  - scope:
      path: ""
      type: learning
    values:
      <<: *default_learning_settings
  - scope:
      path: "_learning/collections"
    values:
      layout: api
      api: learning
      permalink: /api/learning/collections/:title/index.json
      type: collection
      support_paging: false
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      <<: *default_project_settings
  # _companies
  - scope:
      path: ""
      type: companies
    values:
      <<: *default_company_settings
  - scope:
      path: "_companies/collections"
    values:
      layout: api
      api: companies
      permalink: /api/companies/collections/:title/index.json
      type: collection
      support_paging: false
  # _celebrities
  - scope:
      path: ""
      type: celebrities
    values:
      <<: *default_celebrity_settings
  - scope:
      path: "_celebrities/collections"
    values:
      layout: api
      api: celebrities
      permalink: /api/celebrities/collections/:title/index.json
      type: collection
      support_paging: false
  # _events
  - scope:
      path: ""
      type: events
    values:
      <<: *default_event_settings
  - scope:
      path: "_events/collections"
    values:
      layout: api
      api: events
      permalink: /api/events/collections/:title/index.json
      type: collection
      support_paging: false
  # _newsletter
  - scope:
      path: ""
      type: newsletter
    values:
      <<: *default_newsletter_settings
  # _terms
  - scope:
      path: ""
      type: terms
    values:
      <<: *default_taxonomy_settings
  # categories
  - scope:
      path: _terms/categories
      type: terms
    values:
      <<: *category_settings
  # tags
  - scope:
      path: _terms/tags
      type: terms
    values:
      <<: *tag_settings
  # topics
  - scope:
      path: _terms/topics
      type: terms
    values:
      <<: *topic_settings
  # apis
  - scope:
      path: "api/*/*"
    values:
      layout: api
      permalink: /:path/index.json
      support_paging: true

# Compress HTML in Jekyll
# http://jch.penibelst.de/
compress_html:
  clippings: []
  comments: []
  ignore:
    envs: [development, production]
  blanklines: false
  profile: false
  startings: []
  endings: []

theme:

# Use the following Jekyll plug-ins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-relative-links # Convert relative links to md files to their rendered equivalents
  - jemoji # Enable Emoji

relative_links:
  enabled: true
  collections: true

include:
  - .htaccess

# Exclude these files from your production _site
exclude:
  - "src/jify"
  - CNAME
  - README.md
  - Gemfile
  - Gemfile.lock
  - .SynologyWorkingDirectory
  - .cache
  - .sass-cache

incremental: false

sass:
  sass_dir: ./src
  style: compressed

includes_dir: ./src
layouts_dir: ./src/system/_layouts
